
// Generated by Wrangler
// After adding bindings to `wrangler.toml`, regenerate this interface via `npm run cf-typegen`
interface Env {
    FAUCET_ADDRESS_PREFIX: string;
    FAUCET_NUM_ACCOUNTS: number;
    FAUCET_COOLDOWN_TIME: string;
    FAUCET_GAS_LIMIT: string;
    FAUCET_GAS_PRICE: string;
    FAUCET_LOGGING: boolean;
    FAUCET_MEMO: string;
    FAUCET_MNEMONIC: string;
    FAUCET_PATH_PATTERN: string;
    FAUCET_RPC_URL: string;
    FAUCET_TOKENS: string;
}
